# node_exporter
node_exporter_version: '1.6.1'

# promtail
promtail_version: '2.9.0'

# go
go_version: '1.21.6'

# cosmovisor
cosmovisor_version: 'latest'

# Snapshot base URL
snapshot_base_url: 'https://polkachu.com/api/v2/chain_snapshots'
