network: bitsong
folder: '.bitsongd'
daemon: bitsongd
chain_id: bitsong-2b
node_version: v0.11.0
repo: https://github.com/bitsongofficial/go-bitsong
genesis: https://raw.githubusercontent.com/bitsongofficial/networks/master/bitsong-2b/genesis.json
seeds: 'ffa27441ca78a5d41a36f6d505b67a145fd54d8a@95.217.156.228:26656,efd52c1e56b460b1f37d73c8d2bd5f860b41d2ba@65.21.62.83:26656'
minimum_gas_price: ''
custom_port_prefix: 160

# [Optional] Cosmos exporter
denom: btsg
denom_prefix: bitsong

# [Optional] Snapshot
snapshot_server: 1
snapshot_hour: 1
snapshot_minute: 30
