network: cerberus
folder: '.cerberus'
daemon: cerberusd
chain_id: cerberus-chain-1
node_version: v1.0.1
repo: https://github.com/cerberus-zone/cerberus.git
genesis: 'https://raw.githubusercontent.com/cerberus-zone/cerberus_genesis/main/genesis.json'
seeds: '4c3abff6e4a3e93b84babfc95df854861f83ac82@cerberus-seed.blockpane.com:26656'
peers: 'aaa2eba32286074fb575a48e033ac2ba7f4c94e6@98.113.93.139:26661,89ee9a502d4d84e5632a1f5b17cbedfb0aaae088@116.202.133.77:26656,1d7be8ba88c4d1d36d94f493b31018b832ecb5be@116.202.223.110:26656,7bc4a76ea8ada51695bb2797ae24eec011f4bb86@194.163.175.85:26656,17e1441d760583ab5cf79a93ea01ced685948bf7@168.119.110.93:26656,d7f578c4295c7cf05164a2f786601050bf2f2356@142.132.202.98:46656,21cca2db122c48a11f426799131ef08235d46671@148.251.177.45:10656,bae90c7f3aca48e7ae8b3e28dc3b01a2143f068e@194.163.169.187:26656,2cee125f1f1d852b08ef3530154da2eb54ed72ac@66.94.127.8:26656,081e114c7452e3b148cc1a796d75f702b60b0219@85.237.192.125:26656,22e0968f91aba1b3d4d9ad2db2ae47af8cc0a81a@34.139.66.39:26656,c346db0db91a940e87e9ae7df28c3d4947672f54@65.108.121.239:26656,5180ecb20880706a14f99b8982f37a5c23da21ec@65.21.235.249:26656,f03e64d46713068da60b096d528053a57e0e5fec@157.90.36.33:29563'
minimum_gas_price: '0.025ucrbrus'
