network: cheqd
folder: '.cheqdnode'
daemon: cheqd-noded
chain_id: cheqd-mainnet-1
node_version: v0.6.0
repo: https://github.com/cheqd/cheqd-node
genesis: https://raw.githubusercontent.com/cheqd/cheqd-node/main/networks/mainnet/genesis.json
seeds: '258a9bfb822637bfca87daaab6181c10e7fd0910@seed1.eu.cheqd.net:26656,f565ff792b20977face9817df6acb268d41d4092@seed2.eu.cheqd.net:26656,388947cc7d901c5c06fedc4c26751634564d68e6@seed3.eu.cheqd.net:26656,9b30307a2a2819790d68c04bb62f5cf4028f447e@seed1.ap.cheqd.net:26656'
minimum_gas_price: '25ncheq'
custom_port_prefix: 161

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
