network: comdex
folder: '.comdex'
daemon: comdex
chain_id: comdex-1
node_version: v0.1.1
repo: https://github.com/comdex-official/comdex.git
genesis: 'https://raw.githubusercontent.com/comdex-official/networks/main/mainnet/comdex-1/genesis.json'
peers: 'f74518ad134630da8d2405570f6a3639954c985f@65.0.173.217:26656,d478882a80674fa10a32da63cc20cae13e3a2a57@43.204.0.243:26656,61d743ea796ad1e1ff838c9e84adb38dfffd1d9d@15.235.9.222:26656,b8468f64788a17dbf34a891d9cd29d54b2b6485d@194.163.178.25:26656,d8b74791ee56f1b345d822f62bd9bc969668d8df@194.163.128.55:36656,81444353d70bab79742b8da447a9564583ed3d6a@164.68.105.248:26656,5b1ceb8110da4e90c38c794d574eb9418a7574d6@43.254.41.56:26656,98b4522a541a69007d87141184f146a8f04be5b9@40.112.90.170:26656,9a59b6dc59903d036dd476de26e8d2b9f1acf466@195.201.195.111:26656'
seeds: 'aef35f45db2d9f5590baa088c27883ac3d5e0b33@3.108.102.92:26656,7ca14a1d156299999eba9c394ca060368022d52f@54.194.178.110:26656,08ab4552a74dd7e211fc79432918d35818a67189@52.69.58.231:26656,449a0f1b7dafc142cf23a1f6166bbbf035edfb10@13.232.85.66:26656,5b27a6d4cf33909c0e5b217789e7455e261941d1@15.222.29.207:26656'
minimum_gas_price: '0.025ucmdx'
custom_port_prefix: 31

# [Optional] Cosmos exporter
denom: cmdx
denom_prefix: comdex

# [Optional] Snapshot
snapshot_server: 1
snapshot_hour: 2
snapshot_minute: 0
