network: crescent
folder: '.crescent'
daemon: crescentd
chain_id: 'crescent-1'
node_version: 'v1.1.0'
repo: 'https://github.com/crescent-network/crescent'
genesis: 'https://github.com/crescent-network/launch/blob/main/mainnet/crescent-1/genesis.json.tar.gz?raw=true'
genesis_processing: targz
minimum_gas_price: '0.01ucre,0.01bucre'
seeds: '929f22a7b04ff438da9edcfebd8089908239de44@18.180.232.184:26656'
peers: '68787e8412ab97d99af7595c46514b9ab4b3df45@54.250.202.17:26656,0ed5ed53ec3542202d02d0d47ac04a2823188fc2@52.194.172.170:26656,04016e800a079c8ee5bdb9361c81c026b6177856@34.146.27.138:26656,24be64cd648958d9f685f95516cb3b248537c386@52.197.140.210:26656,83b3ba06b43fda52c048934498c6ee2bd4987d2d@3.39.144.72:26656,7e59c83196fdc61dcf9d36c42776c0616bc0fc8c@3.115.85.120:26656,06415494b86316c55245d162da065c3c0fee83fc@172.104.108.21:26656,4293ce6b47ee2603236437ab44dc499519c71e62@45.76.97.48:26656,4113f7496857d3f161921c7af8d62022551a7e6b@167.179.75.240:26656,2271e3739ea477bce0df39dd9e95f8b952a2106e@198.13.62.7:26656,b34115ba926eb12059ca0ade4d1013cac2f8d289@crescent-mainnet-01.01node.com:26656,d7556e41ba2f333379f6d87b1af3cce2ca545f79@34.88.102.246:26656,26011ac36240fb49852cc7196f71a1884434b8c4@34.84.227.139:26656,b840926fb6a2bd04fc70e501002f9286655c9179@52.199.91.143:30732,86030850dd635cab1f136979568087407a025491@46.101.153.158:26656'
custom_port_prefix: 45

# [Optional] Snapshot
snapshot_hour: 5
snapshot_minute: 0
