network: gravity
folder: '.gravity'
daemon: gravity
chain_id: gravity-bridge-3
node_version: 'v1.6.7'
repo: 'https://github.com/Gravity-Bridge/Gravity-Bridge'
binary: 'https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/v1.6.7/gravity-linux-amd64'
genesis: 'https://raw.githubusercontent.com/Gravity-Bridge/gravity-docs/main/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:42656'
custom_port_prefix: 142

# [Optional] Cosmos exporter
denom: grav
denom_prefix: gravity

# [Optional] Snapshot
snapshot_server: 1
snapshot_hour: 4
snapshot_minute: 0
