network: lum
folder: '.lumd'
daemon: lumd
chain_id: lum-network-1
node_version: v1.1.3
repo: https://github.com/lum-network/chain
genesis: https://raw.githubusercontent.com/lum-network/mainnet/master/genesis.json
seeds: '19ad16527c98b782ee35df56b65a3a251bd99971@peer-1.mainnet.lum.network:26656'
minimum_gas_price: ''
custom_port_prefix: 167

# [Optional] Cosmos exporter
denom: lum
denom_prefix: lum 

# [Optional] Snapshot
snapshot_server: 1
snapshot_hour: 1
snapshot_minute: 30
