network: lum
folder: '.lumd'
daemon: lumd
chain_id: lum-network-1
node_version: v1.0.5
repo: https://github.com/lum-network/chain.git
genesis: 'https://raw.githubusercontent.com/lum-network/mainnet/master/genesis.json'
seeds: '19ad16527c98b782ee35df56b65a3a251bd99971@peer-1.mainnet.lum.network:26656'
peers: 'b47626b9d78ed7ed3c413304387026f907c70cbe@peer-0.mainnet.lum.network:26656,5ea36d78ae774c9086c2d3fc8b91f12aa4bf3029@46.101.251.76:26656,a7f8832cb8842f9fb118122354fff22d3051fb83@3.36.179.104:26656,9afac13ba62fbfaf8d06867c30007162511093c0@54.214.134.223:26656,433c60a5bc0a693484b7af26208922b84773117e@34.209.132.0:26656,8fafab32895a31a0d7f17de58eddb492c6ced6d1@185.194.219.83:36656,c06eae3d9ea779710bca44e03f57e961b59d63f1@82.65.223.126:46656,4166de0e7721b6eec9c776abf2c38c40e7f820c5@202.61.239.130:26656,5a29947212a2615e43dac54deb55356a162e173a@35.181.76.160:26656,2cda4d97de0449878da10e456b176dd0720fbcec@62.171.129.174:26656'
minimum_gas_price: '0.001ulum'
