network: passage
folder: '.passage'
daemon: passage
chain_id: passage-1
node_version: v1.0.0
repo: https://github.com/envadiv/Passage3D
genesis: 'https://raw.githubusercontent.com/envadiv/mainnet/main/passage-1/genesis.json'
peers: '69975e7afdf731a165e40449fcffc75167a084fc@104.131.169.70:26656,d35d652b6cb3bf7d6cb8d4bd7c036ea03e7be2ab@116.203.182.185:26656,ffacd3202ded6945fed12fa4fd715b1874985b8c@3.98.38.91:26656,8e0b0d4f80d0d2853f853fbd6a76390113f07d72@65.108.127.249:26656,0111da7144fd2e8ce0dfe17906ef6fd760325aca@142.132.213.231:26656'
seeds: 'aebb8431609cb126a977592446f5de252d8b7fa1@104.236.201.138:26656,b6beabfb9309330944f44a1686742c2751748b83@5.161.47.163:26656,7a9a36630523f54c1a0d56fc01e0e153fd11a53d@167.235.24.145:26656'
custom_port_prefix: 56

# [Optional] Cosmos exporter
denom: upasg
denom_prefix: pasg

# [Optional] Snapshot
snapshot_server: 1
snapshot_hour: 8
snapshot_minute: 0
