---
- name: Install from source
  block:
    - name: Clone node repo
      git:
        repo: '{{ repo }}'
        dest: '{{ user_dir }}/{{ network }}'
        version: '{{ node_version }}'
        update: yes
        force: yes
        depth: 1

    - name: Install node
      command: '{{ item }}'
      args:
        chdir: '{{ user_dir }}/{{ network }}'
      with_items:
        - 'make install'
      environment:
        PATH: '{{ path }}'
        GOPATH: '{{ user_dir }}/go'
  when: binary is undefined

- name: Install from binary
  include_tasks: binary_default.yml
  when: binary is defined and binary_processing is not defined

- name: Install from binary zipped
  include_tasks: binary_zip.yml
  when: binary is defined and binary_processing is defined and binary_processing == 'zip'

- name: Install from binary tar gz
  include_tasks: binary_targz.yml
  when: binary is defined and binary_processing is defined and binary_processing == 'targz'

- name: Set chain_id
  command: "{{ user_dir }}/go/bin/{{ daemon }} config chain-id {{ chain_id }}"

- name: Set local node
  command: "{{ user_dir }}/go/bin/{{ daemon }} config node tcp://localhost:{{ custom_port_prefix }}57"
