---
- name: Open prometheus port
  become: true
  ufw:
    rule: allow
    port: '{{ custom_port_prefix }}61'
    proto: tcp
  when:
    - node_exporter|bool == true

- name: Open p2p port
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: "{{ custom_port_prefix }}56"

- name: Install cosmovisor
  command: 'go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@{{ cosmovisor_version }}'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'
  run_once: true

- name: Create cosmovisor directories
  command: "$BINARY_PATH/cosmovisor init $BINARY_PATH/{{ daemon }}"
  environment:
    - BINARY_PATH: '{{ user_dir }}/go/bin'
    - DAEMON_HOME: '{{ user_dir }}/{{ folder }}'
    - DAEMON_NAME: '{{ daemon }}'

- name: copy service file
  become: true
  template:
    src: 'cosmovisor.service.j2'
    dest: '/etc/systemd/system/{{ daemon }}.service'
    owner: root
    group: root
    mode: '0644'

- name: start cosmovisor service
  become: true
  systemd:
    name: '{{ daemon }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
