# Require special installation: https://github.com/Agoric/agoric-sdk/wiki/ag0-to-agd-upgrade-for-mainnet-1-launch
network: agoric
folder: '.agoric'
daemon: agd
chain_id: 'agoric-3'
node_version: 'agoric-upgrade-8'
repo: 'https://github.com/Agoric/ag0'
genesis: 'https://main.agoric.net/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14456'
custom_port_prefix: 144
minimum_gas_price: '0.01ubld,0.005uist'
gas_params: '--fees 2000ubld'

# [Optional] Snapshot
snapshot_hour: 4
snapshot_minute: 30
