network: agoric
folder: '.agoric'
daemon: ag0
chain_id: 'agoric-3'
node_version: 'agoric-upgrade-7'
repo: 'https://github.com/Agoric/ag0'
genesis: 'https://main.agoric.net/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:44656'
custom_port_prefix: 144

# [Optional] Cosmos exporter
denom: bld
denom_prefix: agoric

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 4
snapshot_minute: 30
