network: allora
folder: '.allorad'
daemon: allorad
chain_id: 'allora-mainnet-1'
node_version: 'v0.9.0'
repo: https://github.com/allora-network/allora-chain
genesis: https://raw.githubusercontent.com/allora-network/networks/refs/heads/main/allora-mainnet-1/genesis.json
custom_port_prefix: 267
seeds: '557d0d381bb7edf7e390465cdad8343862cdd025@peer-1.mainnet.allora.network:26656,aa75a17ad0e42c2cf449e3ffcf3f477405571104@peer-2.mainnet.allora.network:26656,d1bdd4803dd928a13bd08c4a6e7e2ea216dfa28c@peer-3.mainnet.allora.network:26656'
peers: '961e7f18a1c3d31a146e7325206e1d37799c3979@seed-1.mainnet.allora.network:26656,ba3193330a8e57d588c51a017a3096c5a0980497@seed-2.mainnet.allora.network:26656'
upgrade_folder: v0.9.0

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
