network: andromeda
folder: '.andromeda'
daemon: andromedad
chain_id: 'andromeda-1'
node_version: 'v2.0.0'
repo: 'https://github.com/andromedaprotocol/andromedad'
genesis: 'https://raw.githubusercontent.com/andromedaprotocol/mainnet/release/genesis.json'
peers: 'fd8f04a2d264411d28c690ae8c9009dc472c0139@65.109.104.72:21256'
custom_port_prefix: 212
minimum_gas_price: '0uandr'
upgrade_folder: v2
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 30
