network: archway
folder: '.archway'
daemon: archwayd
chain_id: archway-1
node_version: 'v9.0.0'
repo: https://github.com/archway-network/archway
genesis: 'https://snapshots.polkachu.com/genesis/archway/genesis.json'
seeds: '3ba7bf08f00e228026177e9cdc027f6ef6eb2b39@35.232.234.58:26656'
custom_port_prefix: 115
minimum_gas_price: '0.0uaarch'
gas_params: '--fees 180000000000000000aarch'
upgrade_folder: v9.0.0
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 15
wasm: 'outside'
