# Note: need to install manually because there is no "make install"
network: axelar
folder: '.axelar'
daemon: axelard
chain_id: 'axelar-dojo-1'
node_version: 'v0.34.1'
repo: 'https://github.com/axelarnetwork/axelar-core'
config_file: 'https://raw.githubusercontent.com/axelarnetwork/axelarate-community/main/configuration/config.toml'
app_file: 'https://raw.githubusercontent.com/axelarnetwork/axelarate-community/main/configuration/app.toml'
genesis: 'https://axelar-mainnet.s3.us-east-2.amazonaws.com/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:15156'
custom_port_prefix: 151
minimum_gas_price: '0.007uaxl'
upgrade_folder: 'v0.34'
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 6
snapshot_minute: 30
#Wed Sep 13 2023 06:23:08
#9,125,262
