# 11
network: band
folder: '.band'
daemon: bandd
chain_id: laozi-mainnet
node_version: v3.1.2
repo: 'https://github.com/bandprotocol/chain'
genesis: 'https://raw.githubusercontent.com/bandprotocol/launch/master/laozi-mainnet/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:22956'
custom_port_prefix: 229
minimum_gas_price: 0.0025uband
update_website_immediately: false
upgrade_folder: v3_1

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
