network: bitsong
folder: '.bitsongd'
daemon: bitsongd
chain_id: bitsong-2b
node_version: v0.21.5
repo: https://github.com/bitsongofficial/go-bitsong
genesis: https://raw.githubusercontent.com/bitsongofficial/networks/master/bitsong-2b/genesis.json
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:16056'
minimum_gas_price: '0btsg'
custom_port_prefix: 160
upgrade_folder: v021
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 45
wasm: 'inside'
