network: carbon
folder: '.carbon'
daemon: carbond
chain_id: carbon-1
node_version: v2.29.0
repo: https://github.com/Switcheo/carbon-bootstrap
genesis: https://github.com/Switcheo/carbon-bootstrap/blob/master/carbon-1/genesis.json?raw=true
binary: https://github.com/Switcheo/carbon-bootstrap/releases/download/v2.29.0/carbond2.29.0-mainnet.linux-amd64.tar.gz
binary_processing: targz
peers: '5ee2c6cb046d62f90cfdb14eb6f124b60a7a150f@65.108.238.103:19656'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:19656'
custom_port_prefix: 196

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
