network: celestia
folder: '.celestia-app'
daemon: celestia-appd
chain_id: celestia
node_version: 'v1.3.0'
repo: https://github.com/celestiaorg/celestia-app.git
genesis: 'https://raw.githubusercontent.com/celestiaorg/networks/master/celestia/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:11656'
custom_port_prefix: 116
minimum_gas_price: '0.002utia'
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 2
snapshot_minute: 0
