network: certik
folder: '.certik'
daemon: certik
chain_id: shentu-2.2
node_version: v2.4.0
repo: https://github.com/ShentuChain/shentu.git
genesis: 'https://raw.githubusercontent.com/certikfoundation/mainnet/main/shentu-2.2/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:40656'
custom_port_prefix: 140

# [Optional] Cosmos exporter
denom: ctk
denom_prefix: certik

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 3
snapshot_minute: 0
