network: chain4energy
folder: '.c4e-chain'
daemon: c4ed
chain_id: 'perun-1'
node_version: v1.4.3
repo: https://github.com/chain4energy/c4e-chain
genesis: https://raw.githubusercontent.com/chain4energy/c4e-chains/main/perun-1/genesis.json
seeds: '8ac87f7f8da5c2a901d64f2c1e86f8b6ee39fef1@seed-m.c4e.apeironnodes.com:41003'
peers: '8ac87f7f8da5c2a901d64f2c1e86f8b6ee39fef1@seed-m.c4e.apeironnodes.com:41003,edca3b826d61d1e5e7d3dc173954de1324f2e512@seed-m.c4e.apeironnodes.com:27003,30e98bbcf5bb29ed4e4ff685fa8fa84fa0ddff51@tenderseed.ccvalidators.com:26008,54515079bae4cadae2f9b511cffeb9447d4bc98d@c4e.seed.bccnodes.com:30656,54ca81dd509cc6160de7f4b479a96b341d8e830e@rpc.c4e.nodexcapital.com:13956'
upgrade_folder: v1.4.3
custom_port_prefix: 272

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
