network: cosmos
folder: '.gaia'
daemon: gaiad
chain_id: cosmoshub-4
node_version: v7.0.1
repo: 'https://github.com/cosmos/gaia'
genesis: 'https://github.com/cosmos/mainnet/blob/master/genesis/genesis.cosmoshub-4.json.gz?raw=true'
genesis_processing: gz
minimum_gas_price: '0.0025uatom'
peers: '3aa86f390e71f416f66dcf68b22b1b640f1fa23d@65.108.131.174:49656'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:49656'
custom_port_prefix: 149

# [Optional] Cosmos exporter
denom: atom
denom_prefix: cosmos

# [Optional] Snapshot
snapshot_server: 1
snapshot_hour: 0
snapshot_minute: 0
