network: cudos
folder: '.cudos'
daemon: cudos-noded
chain_id: 'cudos-1'
node_version: 'v1.0.0'
repo: 'https://github.com/CudoVentures/cudos-builders'
genesis: 'https://github.com/CudoVentures/cudos-builders/blob/v1.0.0/docker/config/genesis.mainnet.json?raw=true'
minimum_gas_price: '0.01acudos'
seeds: 'ff3f0f7b1eecc6844e6512428ef4c7a9448452a8@cluster-1-seed-1.hosts.cudos.org:266566d9beb4d44a530a4a10ebe78ed7717f6083d0c4b@cluster-2-seed-1.hosts.cudos.org:26656,e0f3bcc574ef66ae4561fad0772a4fd1959969af@cluster-3-seed-1.hosts.cudos.org:26656'
peers: 'f196d7cc811a5ab99e4c5dd5c7f3c0135509d1c4@cluster-1-sentry-1.hosts.cudos.org:26656,2cc0a12ff1038509b2ed64719fcddfdded9a04ad@cluster-2-sentry-1.hosts.cudos.org:26656,ab1ec4fb29afc9c0f5a04b7cbd1220b8b30ffea4@cluster-3-sentry-1.hosts.cudos.org:26656,2958b15e9102cb556cc0f1f1bbbfdfc922a16069@mainnet-full-node-01.hosts.cudos.org:26656,eb14f9142ad313297653f84754b1caf60efe75ac@mainnet-full-node-02.hosts.cudos.org:26656'
custom_port_prefix: 123

# [Optional] Snapshot
snapshot_hour: 5
snapshot_minute: 0
