network: desmos
folder: '.desmos'
daemon: desmos
chain_id: desmos-mainnet
node_version: v2.3.1
repo: https://github.com/desmos-labs/desmos
genesis: https://raw.githubusercontent.com/desmos-labs/mainnet/main/genesis.json
seeds: '9bde6ab4e0e00f721cc3f5b4b35f3a0e8979fab5@seed-1.mainnet.desmos.network:26656,5c86915026093f9a2f81e5910107cf14676b48fc@seed-2.mainnet.desmos.network:26656,45105c7241068904bdf5a32c86ee45979794637f@seed-3.mainnet.desmos.network:26656'
minimum_gas_price: ''
custom_port_prefix: 162

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
