network: evmos
folder: '.evmosd'
daemon: evmosd
chain_id: evmos_9001-2
node_version: v13.0.2
repo: https://github.com/tharsis/evmos
genesis: 'https://snapshots.polkachu.com/genesis/evmos/genesis.json'
peers: '425b9969981dd38bbc53c0f3f01593fdca631667@65.108.131.174:13456'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:13456'
minimum_gas_price: '250000000aevmos'
custom_port_prefix: 134
upgrade_folder: v13.0.2
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
