network: firmachain
folder: '.firmachain'
daemon: firmachaind
chain_id: colosseum-1
node_version: v0.3.3
repo: https://github.com/firmachain/firmachain
genesis: https://raw.githubusercontent.com/firmachain/mainnet/main/genesis.json
seeds: 'f89dcc15241e30323ae6f491011779d53f9a5487@mainnet-seed1.firmachain.dev:26656,	04cce0da4cf5ceb5ffc04d158faddfc5dc419154@mainnet-seed2.firmachain.dev:26656,	940977bdc070422b3a62e4985f2fe79b7ee737f7@mainnet-seed3.firmachain.dev:26656'
minimum_gas_price: ''
custom_port_prefix: 164

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
