network: gravity
folder: '.gravity'
daemon: gravity
chain_id: gravity-bridge-3
node_version: 'v1.10.0'
repo: 'https://github.com/Gravity-Bridge/Gravity-Bridge'
binary: 'https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/v1.10.0/gravity-linux-amd64'
binary_processing: default
genesis: 'https://raw.githubusercontent.com/Gravity-Bridge/gravity-docs/main/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14256'
custom_port_prefix: 142
upgrade_folder: antares
gas_params: '--gas=auto --gas-adjustment=1.4'

# [Optional] Snapshot
snapshot_hour: 4
snapshot_minute: 0
