network: injective
folder: '.injectived'
daemon: injectived
chain_id: injective-1
node_version: v1.13.3
repo: https://github.com/InjectiveFoundation/injective-core
genesis: https://raw.githubusercontent.com/InjectiveLabs/mainnet-config/master/10001/genesis.json
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14356'
app_file: https://raw.githubusercontent.com/InjectiveLabs/mainnet-config/master/10001/app.toml
minimum_gas_price: '160000000inj'
custom_port_prefix: 143
update_website_immediately: false
upgrade_folder: v1.13.2

# [Optional] Snapshot
snapshot_hour: 4
snapshot_minute: 0
wasm: 'outside'
