network: kujira
folder: .kujira
daemon: kujirad
chain_id: kaiyo-1
node_version: v0.9.3-1
repo: 'https://github.com/Team-Kujira/core'
genesis: 'https://raw.githubusercontent.com/Team-Kujira/networks/master/mainnet/kaiyo-1.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:11856'
minimum_gas_price: '0.0034ukuji,0.01186factory/kujira1qk00h5atutpsv900x202pxx42npjr9thg58dnqpa72f2p7m2luase444a7/uusk,0.0119ibc/295548A78785A1007F232DE286149A6FF512F180AF5657780FC89C009E2C348F,0.00129ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2,0.01795ibc/47BD209179859CDE4A2806763D7189B6E6FE13A17880FE2B42DE1E6C1E329E23,0.65943ibc/3607EB5B5E64DD1C0E12E07F077FF470D5BC4706AFCBC98FE1BA960E5AE4CE07,160416396197ibc/F3AA7EF362EC5E791FE78A0F4CCC69FEE1F9A7485EB1A8CAB3F6601C00522F10,0.02689ibc/EFF323CC632EC4F747C61BCE238A758EFDB7699C3226565F7C20DA06509D59A5,0.01495ibc/DA59C009A0B3B95E0549E6BF7B075C8239285989FF457A8EDDBB56F10B2A6986,0.03139ibc/A358D7F19237777AF6D8AD0E0F53268F8B18AE8A53ED318095C14D6D7F3B2DB5,0.90403ibc/4F393C3FCA4190C0A6756CE7F6D897D5D1BE57D6CCB80D0BC87393566A7B6602,559196837ibc/004EBF085BBED1029326D56BE8A2E67C08CECE670A94AC1947DF413EF5130EB2,5772801ibc/1B38805B1C75352B28169284F96DF56BDEBD9E8FAC005BDCC8CF0378C82AA8E7,0.01807factory/kujira1643jxg8wasy5cfcn7xm8rd742yeazcksqlg4d7/umnta,0.01194ibc/FE98AAD68F02F03565E9FA39A5E627946699B2B07115889ED812D8BA639576A9,0.00019ibc/E5CA126979E2FFB4C70C072F8094D07ECF27773B37623AD2BF7582AD0726F0F3'
custom_port_prefix: 118
upgrade_folder: v0.9.3
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 7
snapshot_minute: 30
wasm: 'outside'

# price feeder (update with your own)
price_feeder_address: 'kujira1xrrfek3qpz4ja8ccrjklfy064asyqq9kz65he9'
price_feeder_validator: 'kujiravaloper1gp957czryfgyvxwn3tfnyy2f0t9g2p4pnsu9m3'
price_feeder_backend: file
price_feeder_network: mainnet
price_feeder_repo: https://github.com/Team-Kujira/oracle-price-feeder
price_feeder_version: 'v0.9.0'
price_feeder_fee_granter: 'kujira1vkje22mayn72r0a7kna6agv0sqm6k94ry9k6dd'
