network: loyal
folder: '.loyal'
daemon: loyald
chain_id: 'loyal-main-02'
node_version: 'v0.25.3'
repo: 'https://github.com/LoyalLabs/loyal'
genesis: 'https://raw.githubusercontent.com/LoyalLabs/net/main/mainnet/genesis.json'
seeds: 'c145da9f8b6c729287b42b1b3bcb6ca69e1a644e@loyal-seed.netdots.net:27656,44b08595ad0601efcf5149176390a6c2411950f7@pubnode1.joinloyal.io:27656'
custom_port_prefix: 178

# [Optional] Snapshot
snapshot_hour: 7
snapshot_minute: 30
