network: migaloo
folder: '.migalood'
daemon: migalood
chain_id: 'migaloo-1'
node_version: 'v2.2.6'
repo: 'https://github.com/White-Whale-Defi-Platform/migaloo-chain'
genesis: 'https://raw.githubusercontent.com/White-Whale-Defi-Platform/migaloo-chain/release/v1.0.x/networks/mainnet/genesis.json'
seeds: '013226057046995f2fa6cbaaa4a1d90508ddc2c1@tenderseed.ccvalidators.com:26013'
custom_port_prefix: 207
minimum_gas_price: '0uwhale'
upgrade_folder: v2.2.5
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
wasm: 'outside'
