# 2
network: nibiru
folder: '.nibid'
daemon: nibid
chain_id: cataclysm-1
node_version: v2.9.0
repo: https://github.com/NibiruChain/nibiru
genesis: 'https://raw.githubusercontent.com/NibiruChain/Networks/main/Mainnet/cataclysm-1/genesis.json'
peers: ' 200d3c6eec510a3bb5a4224d9be188df37032946@148.251.13.186:19856'
custom_port_prefix: 198
upgrade_folder: v2.9.0
minimum_gas_price: 0.025unibi
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 3
snapshot_minute: 0
wasm: 'inside'

# price feeder (update with your own)
price_feeder_address: ''
price_feeder_validator: 'nibivaloper1cz36jg407s0z4f2vd7u6yc44v480dtpljrhdf6'
price_feeder_network: mainnet
price_feeder_repo: https://github.com/NibiruChain/pricefeeder
price_feeder_version: 'v1.0.5'
