network: nillion
folder: '.nillionapp'
daemon: nilchaind
chain_id: nillion-1
node_version: v0.2.5
repo: https://github.com/NillionNetwork/nilchain
genesis: 'storage.nodes.guru/nillion/genesis.json'
peers: '9da9bd9147db409d1e3c080379d09753c7cc8889@35.214.131.222:26656,f0829a5b4e372cba88dc6a0e1fa765a3d570d5f6@65.108.201.240:28156,66610f3bc7fe380191906f11949bb56d49e948db@65.21.25.55:26656,a8038f2de293de4f28797e1e069bbed858dfb9c6@45.250.252.75:56316,ddd9cf6fa25048e75521035086500076518637d9@160.250.106.104:28156,0e5e4dae6f359062d7bd953ecd84d157aa1e271a@185.189.44.205:26656,f55f7eb02fa05a02cc4186b028a05a2dc7b71d9d@184.107.185.205:18600,28e36e25966cac6ce9d7d9ccc52afb86d44470f6@84.32.32.150:18600,3e775c224282d180c3de6deb3a3c610aea9ccf19@185.119.118.61:26656,17ee0a9654db68c8b0e6b192fe84cf486377d4c8@175.110.114.28:26656,b2c5a8e718816fada192c83ea7d4068752ece574@178.23.126.94:31321,b4a0753efffc6c7704f1f5d22047d5463776ab4f@121.134.209.209:26656'
custom_port_prefix: 281
minimum_gas_price: '0.025unil'

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
