# 6
network: nolus
folder: '.nolus'
daemon: nolusd
chain_id: pirin-1
node_version: v0.8.2
repo: https://github.com/nolus-protocol/nolus-core.git
genesis: 'https://raw.githubusercontent.com/nolus-protocol/nolus-networks/main/mainnet/pirin-1/genesis.json?raw=true'
seeds: ''
peers: b7673d6f61e8696e4fa44dbdb813b5b94be289b6@65.108.238.219:19756
minimum_gas_price: '0.0025unls'
custom_port_prefix: 197
upgrade_folder: v0.8.2
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
wasm: 'outside'
