network: nym
folder: '.nyxd'
daemon: nyxd
chain_id: nyx
node_version: v0.54.2
repo: https://github.com/nymtech/nyxd
genesis: 'https://snapshots.polkachu.com/genesis/nym/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:15356'
custom_port_prefix: 153
upgrade_folder: v0.54.1
update_website_immediately: false
minimum_gas_price: '0.025unym,0.025unyx'

# [Optional] Snapshot
snapshot_hour: 7
snapshot_minute: 0
wasm: 'outside'
