network: odin
folder: '.odin'
daemon: odind
chain_id: odin-mainnet-freya
node_version: v0.7.9
repo: https://github.com/ODIN-PROTOCOL/odin-core
genesis: https://storage.googleapis.com/odin-mainnet-freya/genesis-4.1.json
peers: 'd23013e1a0a82d71d251f96c63609ee88af2e29c@34.38.73.153:26656,3ae5858dbad9c65f07f1bd8ccf6c2bf9e089dbb1@34.78.8.181:26656,5cfe57184c002bf2050b5a1d1d247dccf18784f1@34.78.212.147:26656'
minimum_gas_price: '0.0125loki'
custom_port_prefix: 168

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
wasm: 'outside'
