network: passage
folder: '.passage'
daemon: passage
chain_id: passage-2
node_version: v2.6.0
repo: https://github.com/envadiv/Passage3D
genesis: 'https://raw.githubusercontent.com/envadiv/mainnet/main/passage-2/genesis.json'
peers: '0143bb6f4b43a285fa0ba5fd6993af519f91f3d7@65.108.238.219:15656'
upgrade_folder: v2.6.0
custom_port_prefix: 156
update_website_immediately: true
minimum_gas_price: '12.5upasg'
tendermint: true

# [Optional] Snapshot
snapshot_hour: 8
snapshot_minute: 0
wasm: 'outside'
