network: quicksilver
folder: '.quicksilverd'
daemon: quicksilverd
chain_id: quicksilver-2
node_version: v1.2.2
repo: https://github.com/ingenuity-build/quicksilver.git
genesis: https://raw.githubusercontent.com/ingenuity-build/mainnet/main/genesis.json
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:11156'
custom_port_prefix: 111

# [Optional] Snapshot
snapshot_hour: 5
snapshot_minute: 0
