network: secret
folder: '.secretd'
daemon: secretd
chain_id: secret-4
node_version: v1.10.0
repo: https://github.com/scrtlabs/SecretNetwork/
binary: 'https://github.com/scrtlabs/SecretNetwork/releases/download/v1.3.1/secretnetwork_1.3.1_mainnet_goleveldb_amd64.deb'
binary_processing: 'deb'
genesis: https://github.com/scrtlabs/SecretNetwork/releases/download/v1.2.0/genesis.json
seeds: '6fb7169f7630da9468bf7cc0bcbbed1eb9ed0d7b@scrt-seed-01.scrtlabs.com:26656,ab6394e953e0b570bb1deeb5a8b387aa0dc6188a@scrt-seed-02.scrtlabs.com:26656,9cdaa5856e0245ecd73bd464308fb990fbc53b57@scrt-seed-03.scrtlabs.com:26656'
upgrade_folder: v1.10 # Upgrade need manual intervention because it is run as root
minimum_gas_price: '0.00125uscrt'
custom_port_prefix: 171

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
