network: sei
folder: '.sei'
daemon: seid
chain_id: 'pacific-1'
node_version: 'v3.5.1'
repo: https://github.com/sei-protocol/sei-chain.git
genesis: 'https://snapshots.polkachu.com/genesis/sei/genesis.json'
peers: '380c732671cec070a9a7b979d277e26325f26d61@136.243.67.189:11956'
seed: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:11956'
custom_port_prefix: 119
upgrade_folder: 'v3.5.0'
minimum_gas_price: 0.01usei
update_website_immediately: false
gas_params: '--fees 20000usei'

# [Optional] Snapshot
snapshot_hour: 2
snapshot_minute: 0
wasm: 'outside'

# price feeder
price_feeder_address: 'sei1xrrfek3qpz4ja8ccrjklfy064asyqq9k778ejw'
price_feeder_validator: 'seivaloper1mpe9rdk7ycujge7r9ncjt4ekamgrdcygvzwqe8'
price_feeder_backend: os
price_feeder_network: mainnet
