network: sifchain
folder: '.sifnoded'
daemon: sifnoded
chain_id: sifchain-1
node_version: v1.4.0
repo: https://github.com/Sifchain/sifnode.git
genesis: 'https://raw.githubusercontent.com/Sifchain/networks/master/betanet/sifchain-1/genesis.json.gz'
genesis_processing: gz
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:13256'
minimum_gas_price: '200rowan'
upgrade_folder: 'v1.4.0'
custom_port_prefix: 132
update_website_immediately: false

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 00
