network: sommelier
folder: '.sommelier'
daemon: 'sommelier'
chain_id: sommelier-3
node_version: 'v4.0.1'
repo: 'https://github.com/PeggyJV/sommelier'
genesis: 'https://raw.githubusercontent.com/PeggyJV/sommelier/main/contrib/mainnet/sommelier-3/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:41656'
peers: 'bb1a07db29684f57ce0e24d3bf06c27a6a7ec49a@65.108.131.174:41656'
custom_port_prefix: 141

# [Optional] Snapshot
snapshot_hour: 3
snapshot_minute: 30
