network: stride
folder: '.stride'
daemon: strided
chain_id: stride-1
node_version: 'v18.0.0'
repo: https://github.com/Stride-Labs/stride
genesis: 'https://raw.githubusercontent.com/Stride-Labs/testnet/infra-test/poolparty/infra/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12256'
custom_port_prefix: 122
upgrade_folder: v18
minimum_gas_price: '0.0005ustrd,0.001stuosmo,0.0001stuatom,20000000000staevmos,500000000stinj,0.01stutia,15000000000stadydx,0.001ibc/D24B4564BCD51D3D02D9987D92571EAC5915676A9BD6D9B0C1D0254CB8A5EA34,0.0001ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2,0.01ibc/BF3B4F53F3694B66E13C23107C84B6485BD2B96296BB7EC680EA77BBA75B4801,20000000000ibc/4B322204B4F59D770680FE4D7A565DDC3F37BFF035474B717476C66A4F83DD72,500000000ibc/A7454562FF29FE068F42F9DE4805ABEF54F599D1720B345D6518D9B5C64EA6D2,15000000000ibc/561C70B20188A047BFDE6F9946BDDC5D8AC172B9BE04FF868DFABF819E5A9CCE'
update_website_immediately: false
gas_params: '--gas auto --gas-adjustment 1.5'

# [Optional] Snapshot
snapshot_hour: 8
snapshot_minute: 30
