# 7
network: sunrise
folder: '.sunrise'
daemon: sunrised
chain_id: 'sunrise-1'
node_version: 'v1.2.0'
repo: https://github.com/sunriselayer/sunrise
genesis: https://raw.githubusercontent.com/sunriselayer/network/main/sunrise-1/genesis.json
seeds: '2a30964e07118a0cb03bb1cae9185d37a967230a@a.validator.sunrise-1.sunriselayer.io:26656'
custom_port_prefix: 283
update_website_immediately: false
upgrade_folder: v1.2.0

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
