# 6
network: symphony
folder: '.symphonyd'
daemon: symphonyd
chain_id: symphony-1
node_version: 'v1.0.8'
repo: https://github.com/Orchestra-Labs/symphony
genesis: 'https://snapshots.polkachu.com/genesis/symphony/genesis.json'
peers: '0d04642a315f926a005d9ffac8a63bc56594362c@65.108.238.219:29156'
custom_port_prefix: 291
minimum_gas_price: '0.025unote'
upgrade_folder: v1.0.8

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
