network: terraclassic
folder: '.terra'
daemon: terrad
chain_id: 'columbus-5'
node_version: 'v2.2.1'
repo: https://github.com/terra-money/classic-core
genesis: 'https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/columbus-5-genesis.json'
seeds: ''
minimum_gas_price: '0.015uluna'
custom_port_prefix: 117
upgrade_folder: 'v5'
