network: xpla
folder: '.xpla'
daemon: xplad
chain_id: 'dimension_37-1'
node_version: 'v1.2.2'
repo: https://github.com/xpladev/xpla
genesis: https://raw.githubusercontent.com/xpladev/mainnet/main/dimension_37-1/genesis.json
seeds: 'e7b6016ce5663a69ba71a982072315545eb0d5f6@seed.xpla.delightlabs.io:26656'
peers: '15efa0a83dff372752369cc984492d9ee72f332b@54.81.115.88:26656,e0d49fdef6aff95ed290ca4acafa2fdd312abd99@35.79.122.205:26656,d5c5908a5390b2278180ce975d94d4a43da4952b@34.89.191.254:26656'
custom_port_prefix: 201
upgrade_folder: EVM

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
wasm: 'inside'
