# 5
network: zetachain
folder: '.zetacored'
daemon: zetacored
chain_id: zetachain_7000-1
node_version: v15.0.0
repo: 'https://github.com/zeta-chain/network-athens3'
binary: 'https://github.com/zeta-chain/node/releases/download/v15.0.0/zetacored-linux-amd64'
binary_processing: default
genesis: 'https://snapshots.polkachu.com/genesis/zetachain/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:22556'
peers: '7389091027fc8858b18d4ca6ef58506ef446ddef@65.109.104.72:22556'
custom_port_prefix: 225
gas_params: '--chain-id zetachain_7000-1'

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
