---
- name: Create directory
  file:
    path: '{{ user_dir }}/genesis'
    state: directory
    mode: '0755'

- name: Copy genesis script
  template:
    src: 'genesis.sh.j2'
    dest: '{{ user_dir }}/genesis/{{ network }}.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0700'
