---
- name: install apt packages
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  loop:
    - make
    - build-essential
    - gcc
    - git
    - jq
    - chrony

- name: Download go
  get_url:
    url: 'https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz'
    dest: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    mode: '0700'

- name: unarchive go
  unarchive:
    src: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    remote_src: yes
    dest: '/usr/local/'
    owner: root
    group: root
    mode: 755

- name: Go get cosmovisor
  command: 'go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@latest'
  environment:
    PATH: '{{ path }}'
    GOPATH: '/home/ubuntu/go'

- name: copy bash_profile
  template:
    src: 'profile.j2'
    dest: '/home/ubuntu/.profile'
    owner: ubuntu
    group: ubuntu
    mode: '600'

- name: Source bash_profile
  shell: |
    set -o pipefail
    source /home/ubuntu/.profile
  args:
    executable: /bin/bash
