---
- name: Create directory
  file:
    path: '{{ user_dir }}/prune'
    state: directory
    mode: '0755'

- name: Copy prune script
  template:
    src: 'prune.sh.j2'
    dest: '{{ user_dir }}/prune/{{ network }}.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0700'
