- name: Install unzip
  apt:
    name: unzip
    state: latest

- name: download genesis zip file
  get_url:
    url: '{{ genesis }}'
    dest: '/tmp/genesis.zip'
    mode: '0700'

- name: unarchive genesis
  unarchive:
    src: '/tmp/genesis.zip'
    remote_src: yes
    dest: '{{ user_dir }}/{{ folder }}/config'
    mode: '0644'
