# testnet0
network: cosmos
folder: '.gaia'
daemon: gaiad
chain_id: provider
node_version: v26.0.0-rc0
repo: 'https://github.com/cosmos/gaia'
genesis: 'https://snapshots.polkachu.com/testnet-genesis/cosmos/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:14956'
custom_port_prefix: 149
upgrade_folder: v26.0.0
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
wasm: outside
