network: cosmos
folder: '.gaia'
daemon: gaiad
chain_id: provider
node_version: v12.0.0-rc0
repo: 'https://github.com/cosmos/gaia'
genesis: 'https://raw.githubusercontent.com/cosmos/testnets/master/replicated-security/provider/provider-genesis.json'
seeds: '08ec17e86dac67b9da70deb20177655495a55407@provider-seed-01.rs-testnet.polypore.xyz:26656,4ea6e56300a2f37b90e58de5ee27d1c9065cf871@provider-seed-02.rs-testnet.polypore.xyz:26656'
custom_port_prefix: 149
upgrade_folder: v12
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
