# testnet4
network: elys
folder: '.elys'
daemon: elysd
chain_id: 'elysicstestnet-1'
node_version: v6.8.0-rc0
repo: https://github.com/elys-network/elys
genesis: https://raw.githubusercontent.com/elys-network/networks/refs/heads/main/testnet/elysicstestnet-1/genesis.json
peers: '4771b02434d797b9728a072b2373e7146fc7bb01@136.243.17.170:33656,5e1d194bdc4be80988ded0e24b34f9f3c0519052@5.79.98.1:57656,a755cd3d49083cd7792392b766254427b7498a85@85.214.204.245:26756,92bdb02828a5479771ce5d2ac9bbdf4d243fa304@51.178.76.62:36656,24d9cdf21a865336f4012262a212a87753df4207@peer-elysicstestnet.apeironnodes.com:50002,7c7a172b5d99f6bf2a91468e6d16c41c677233ee@65.108.234.115:28856,e33be9bff9eac0ee4044ad1039be7e8d94bb992c@65.109.58.158:22056'
custom_port_prefix: 220
minimum_gas_price: '0.01uelys,0.001ibc/F082B65C88E4B6D5EF1DB243CDA1D331D002759E938A0F5CD3FFDC5D53B3E349,0.0002ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9,11395000000ibc/E925EC46A2F4B84815DB7218ADF272989DADD18372C779F68DB31A6BC4F91B7D'
upgrade_folder: v6.8-rc0

update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 3
snapshot_minute: 30
wasm: 'outside'
