network: elys
folder: '.elys'
daemon: elysd
chain_id: 'elystestnet-1'
node_version: 'v0.13.0'
repo: https://github.com/elys-network/elys
genesis: https://rpc.testnet.elys.network/genesis
peers: 'ae22b82b1dc34fa0b1a64854168692310f562136@198.27.74.140:26656'
custom_port_prefix: 220
upgrade_folder: 'v0.13.0'
update_website_immediately: true
minimum_gas_price: '0.0018ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65,0.00025ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2,0.00025uelys'

# [Optional] Snapshot
snapshot_hour: 3
snapshot_minute: 30
