# testnet4
network: fuel
folder: '.fuelsequencer'
daemon: fuelsequencerd
chain_id: 'seq-testnet-2'
node_version: 'seq-testnet-2'
repo: TBD
genesis: https://snapshots.polkachu.com/testnet-genesis/fuel/genesis.json
peers: '3a0b4118c01addd33d5add81783805d5add2fb17@80.64.208.17:26656'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:29656'
custom_port_prefix: 296
minimum_gas_price: '10test'
upgrade_folder: features-and-optimisations

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
