network: jackal
folder: '.canine'
daemon: canined
chain_id: lupulella-2
node_version: v3.0.0-rc.3
repo: https://github.com/JackalLabs/canine-chain
genesis: 'https://raw.githubusercontent.com/JackalLabs/jackal-chain-assets/main/testnet/genesis.json'
seeds: '84f520678ef59ea02f942fa6323ec562ca5a3249@45.79.161.178:26656,cecc087977336da1e9ccd2c50097cd9e7d5e1874@141.95.33.39:26656'
minimum_gas_price: 0.002ujkl
custom_port_prefix: 175
upgrade_folder: 'v3'
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 4
snapshot_minute: 0
