network: kichain
folder: '.kid'
daemon: kid
chain_id: kichain-t-4
node_version: 5.0.0-beta
repo: https://github.com/KiFoundation/ki-tools.git
binary: https://github.com/KiFoundation/ki-tools/releases/download/4.0.0-beta/kid-testnet-4.0.0-beta-linux-amd64
genesis: 'https://raw.githubusercontent.com/KiFoundation/ki-networks/v0.1/Testnet/kichain-t-4/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:13556'
custom_port_prefix: 135
upgrade_folder: v5

# [Optional] Snapshot
snapshot_hour: 2
snapshot_minute: 30
wasm: 'outside'
