network: kujira
folder: .kujira
daemon: kujirad
chain_id: harpoon-4
node_version: v0.8.8
repo: 'https://github.com/Team-Kujira/core'
genesis: 'https://raw.githubusercontent.com/Team-Kujira/networks/master/testnet/harpoon-4.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:11856'
minimum_gas_price: '0.00125ukuji'
custom_port_prefix: 118
upgrade_folder: v0.8.5
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 7
snapshot_minute: 30
wasm: 'outside'

# price feeder (update with your own)
price_feeder_address: 'kujira1jt9w26mpxxjsk63mvd4m2ynj0af09csljfu7ym'
price_feeder_validator: 'kujiravaloper1gp957czryfgyvxwn3tfnyy2f0t9g2p4pnsu9m3'
price_feeder_backend: file
price_feeder_network: testnet
price_feeder_repo: https://github.com/Team-Kujira/oracle-price-feeder
price_feeder_version: 'v0.2.0'
