network: lava
folder: '.lava'
daemon: lavad
chain_id: lava-testnet-1
node_version: v0.22.0
repo: https://github.com/lavanet/lava
genesis: 'https://raw.githubusercontent.com/lavanet/lava-config/main/testnet-2/genesis_json/genesis.json'
binary: 'https://lava-binary-upgrades.s3.amazonaws.com/testnet-2/cosmovisor-upgrades/cosmovisor-upgrades.zip'
binary_processing: zip
seeds: '3a445bfdbe2d0c8ee82461633aa3af31bc2b4dc0@testnet2-seed-node.lavanet.xyz:26656,e593c7a9ca61f5616119d6beb5bd8ef5dd28d62d@testnet2-seed-node2.lavanet.xyz:26656'
peers: '5e068fccd370b2f2e5ab4240a304323af6385f1f@172.93.110.154:27656'
minimum_gas_price: '0ulava'
custom_port_prefix: 199
gas_params: '--gas auto --gas-adjustment 1.5'
upgrade_folder: v0.22.0

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
