# testnet3
network: neutron
folder: '.neutrond'
daemon: neutrond
chain_id: pion-1
node_version: v9.1.0
repo: 'https://github.com/neutron-org/neutron'
genesis: 'https://snapshots.polkachu.com/testnet-genesis/cosmos/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:19156'
upgrade_folder: v9.1.0
custom_port_prefix: 191
update_website_immediately: true
minimum_gas_price: '0untrn'

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
wasm: 'outside'
