# testnet0
network: odiseo
folder: '.achilles'
daemon: achillesd
chain_id: ithaca-1
node_version: v1.0.2
repo: https://github.com/daodiseomoney/Achilles
genesis: 'https://snapshots.polkachu.com/testnet-genesis/odiseo/genesis.json'
peers: '8dceb983d6e50c5d3b0a23fc1d54daeb72d790e2@65.109.113.233:31356'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:31356'
custom_port_prefix: 313
minimum_gas_price: '0.25uodis'
update_website_immediately: true

snapshot_hour: 0
snapshot_minute: 0
