network: ollo
folder: '.ollo'
daemon: ollod
chain_id: ollo-testnet-1
node_version: v0.0.1
repo: 'https://github.com/OLLO-Station/ollo'
genesis: https://raw.githubusercontent.com/OLLO-Station/networks/master/ollo-testnet-1/genesis.json
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:18156'
custom_port_prefix: 181

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
