network: osmosis
folder: '.osmosisd'
daemon: osmosisd
chain_id: osmo-test-5
node_version: v19.0.0-rc0
repo: https://github.com/osmosis-labs/osmosis
genesis: 'https://genesis.osmotest5.osmosis.zone/genesis.json'
seeds: 'bb197876fd952d245ef6377e3651c157e3d7ed81@157.245.26.231:26656,7c2b9e76be5c2142c76b429d9c29e902599ceb44@157.245.21.183:26656'
peers: '9df5654683bb903f582d41b7b2e119b29b833cf1@46.4.5.45:12556'
custom_port_prefix: 125
upgrade_folder: v19
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
wasm: 'outside'
