network: osmosis
folder: '.osmosisd'
daemon: osmosisd
chain_id: osmo-test-5
node_version: v16.0.0-rc2-testnet
repo: https://github.com/osmosis-labs/osmosis
genesis: 'https://genesis.osmotest5.osmosis.zone/genesis.json'
seeds: 'bb197876fd952d245ef6377e3651c157e3d7ed81@157.245.26.231:26656,7c2b9e76be5c2142c76b429d9c29e902599ceb44@157.245.21.183:26656'
peers: '5379659b30958efbd17ba4ce81e43600e8eb04bc@10.245.194.97:26656,bb197876fd952d245ef6377e3651c157e3d7ed81@10.244.2.237:26656, c7bcc765a373f662cbe9bfe80fb91806b21f277e@10.245.183.93:26656,27d5d4c0b3a4cb0b1a0a51212dc287521fe124cc@10.245.186.64:26656,51084fccec1c309a415e89d39e6f0881c49493ed@95.217.144.107:12556'
custom_port_prefix: 125
upgrade_folder: v16
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
wasm: 'outside'
