# need custom install
network: quasar
folder: '.quasarnode'
daemon: quasarnoded
chain_id: quasar-test-1
node_version: v1.0.1-rc-testnet
repo: https://github.com/quasar-finance/quasar-preview
genesis: https://raw.githubusercontent.com/quasar-finance/networks/main/quasar-test-1/definitive-genesis.json
peers: '56e0289842252644780e6e49407824186dd31f6f@65.109.23.114:18256'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:18256'
custom_port_prefix: 182
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
wasm: 'outside'
