network: stride
folder: '.stride'
daemon: strided
chain_id: 'stride-internal-1'
node_version: 'v15.0.0-testnet'
repo: https://github.com/Stride-Labs/stride.git
genesis: https://snapshots.polkachu.com/testnet-genesis/stride/genesis.json
peers: '3d327d32da88b983ede3f76e0cf76580ffc5b79e@stride-direct.testnet-1.stridenet.co:26656'
custom_port_prefix: 122
upgrade_folder: v15
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 8
snapshot_minute: 30
