# testnet1
network: tacchain
folder: '.tacchaind'
daemon: tacchaind
chain_id: 'tacchain_2391-1'
node_version: 'v1.0.2'
repo: https://github.com/TacBuild/tacchain.git
genesis: https://snapshots.polkachu.com/testnet-genesis/tacchain/genesis.json
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:32156'
custom_port_prefix: 321
update_website_immediately: true
minimum_gas_price: '25000000000utac'
upgrade_folder: v1.0.2

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 0
