network: archway
folder: '.archway'
daemon: archwayd
chain_id: torii-1
node_version: 'v0.0.5'
repo: https://github.com/archway-network/archway
genesis: 'https://raw.githubusercontent.com/archway-network/testnets/main/torii-1/genesis.json'
peers: 'dcc82542a94ab6407733802dd50c098da6f27f72@35.184.247.99:26656,facf38daac7cbbdcbaf87f531225d6a621cea483@15.235.10.78:26656,83b18e67dca836a838361496a7c87696a488fd05@65.108.99.224:26656,07fd2c5b8838dfc80ff1e9c5577006b552fcb98c@206.221.181.234:46656,c5ca4cb89df8c194e6b404f54be0e27c1258377b@95.214.55.210:26756,ece6b901c278f91410b798edef805ba1d358c660@59.13.223.197:30273,b1cedcd284964d7657d597541ec9516fa3392cd1@185.234.69.139:26656,ce1e6c7a84ab3f8e2fd87d4aef0f95da774a5e98@159.69.11.174:26656,cb1534d2ad2fedb1168b4052f04ede5b12428068@51.250.111.252:26656,2b0c484615d9bafd6cc339c588e366dd9b000221@54.180.95.251:26656,2e422fe3956b7ea2a868dbe832e8cd9af5203ea6@65.108.75.32:26656,ca8dca9c9a475b145af9cbce135d013e060649dd@65.108.194.40:26686,dcc82542a94ab6407733802dd50c098da6f27f72@35.184.247.99:26656'
custom_port_prefix: 115
