network: teritori
folder: '.teritorid'
daemon: teritorid
chain_id: teritori-testnet-v2
node_version: teritori-testnet-v2
repo: https://github.com/TERITORI/teritori-chain
genesis: https://raw.githubusercontent.com/TERITORI/teritori-chain/main/testnet/teritori-testnet-v2/genesis.json
seeds: ''
peers: 'c1fdbc3d0679bcaf4cfe3aeaf5247ba12b7daa6f@49.12.236.218:26656,0b42fd287d3bb0a20230e30d54b4b8facc412c53@176.9.149.15:26656,2f394edda96be07bf92b0b503d8be13d1b9cc39f@5.9.40.222:26656,8ce81af6b4acee9688b9b3895fc936370321c0a3@78.46.106.69:26656'
minimum_gas_price: ''
custom_port_prefix: 158
