# this node require special build
network: nois
folder: '.noisd'
daemon: noisd
chain_id: nois-testnet-003
node_version: 'v1.1.2'
repo: https://github.com/noislabs/full-node
genesis: 'https://raw.githubusercontent.com/noislabs/testnets/main/nois-testnet-003/genesis.json'
peers: 'bf5bbdf9ac1ccd72d7b29c3fbcc7e99ff89fd053@node-0.noislabs.com:26656'
minimum_gas_price: '0.05unois'
custom_port_prefix: 173
