# network: umee
# folder: '.umee'
# daemon: umeed
# chain_id: canon-1
# node_version: 'v1.0.3'
# repo: https://github.com/umee-network/umee.git
# genesis: 'https://raw.githubusercontent.com/umee-network/testnets/main/networks/canon-1/genesis.json'
# peers: 'dc1b1b89a83873f20b613cdb1361f932afb84a97@35.215.72.45:26656,5e01b69ead6e0781af0361d3ec4e436d96dba932@35.215.98.106:26656,94ac8328b4b9f45b6f7b8e9569ae0253dc53c7eb@35.212.143.125:26656'
# custom_port_prefix: 136
network: umee
folder: '.umee'
daemon: umeed
chain_id: champagne-1
node_version: 'v1.1.2'
repo: https://github.com/umee-network/umee.git
genesis: 'https://raw.githubusercontent.com/umee-network/testnets/main/networks/champagne-1/genesis.json'
peers: 'c27f331e55a35c60aab5363e31209d92028aa15e@35.215.123.79:26656'
custom_port_prefix: 136
