network: juno
folder: .juno
daemon: junod
chain_id: uni-5
node_version: v9.0.0
repo: https://github.com/CosmosContracts/juno
genesis: https://raw.githubusercontent.com/CosmosContracts/testnets/main/uni-5/genesis.json
peers: 'e0fbaf1ef89afad23444e67b334bdf78a4b598fd@65.108.71.92:52656,edc35b09613096598e20f8508c977806093d7eec@194.61.28.217:26656,ed90921d43ede634043d152d7a87e8881fb85e90@65.108.77.106:26709,ec41af656b3450050ae27559b66b877373c44861@65.21.122.47:26656,4a91597dfe3ec715bbf6def225066fbb6ad86cfe@207.180.204.112:36656,f79ce2fab55e56b408d76ddcbc1c82c1a90e315b@54.74.146.114:26656'
minimum_gas_price: '0.0025ujunox'
custom_port_prefix: 126
