network: juno
folder: .juno
daemon: junod
chain_id: uni-3
node_version: v7.0.0-alpha.2
repo: https://github.com/CosmosContracts/juno
genesis: https://raw.githubusercontent.com/CosmosContracts/testnets/main/uni-3/genesis.json
peers: 'ddaa333eba3d8ac43249dcd59451aad28f190d70@162.55.128.249:36656,f79ce2fab55e56b408d76ddcbc1c82c1a90e315b@172.31.44.248:26656'
minimum_gas_price: '0.025ujunox'
custom_port_prefix: 126
