network: xion
folder: '.xiond'
daemon: xiond
chain_id: xion-testnet-1
node_version: v0.3.3
repo: https://github.com/burnt-labs/xion.git
genesis: 'https://files.xion-testnet-1.burnt.com/genesis.json'
seeds: '7900d5f177228def24170f9631db76afab20278e@seed.xion-testnet-1.burnt.com:11656'
peers: '93db3539d6cc9603bbb6b9e43bfb473bdaff7e4b@sentry-use1a.xion-testnet-1.burnt.com:32656,0f2ccb6d7e8f233c03f91dee690f5ff714319fba@sentry-use1b.xion-testnet-1.burnt.com:33656,f684e3873191d62a74e5431202581d99fe3439b7@sentry-use1c.xion-testnet-1.burnt.com:34656'
upgrade_folder: v3
update_website_immediately: true
custom_port_prefix: 223

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 30
wasm: 'outside'
