# testnet0
network: xrp
folder: '.exrpd'
daemon: exrpd
chain_id: xrplevm_1449000-1
node_version: v9.0.0
repo: https://github.com/xrplevm/node.git
genesis: 'https://raw.githubusercontent.com/xrplevm/networks/refs/heads/main/testnet/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:31256'
minimum_gas_price: '0axrp'
custom_port_prefix: 300
update_website_immediately: true
upgrade_folder: v9.0.0

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 30
