# testnet0
network: zkcloud
folder: '.zkcloud'
daemon: zkcloudd
chain_id: 'deluge-1'
node_version: 'v0.2.0'
repo: 'https://github.com/thezkcloud/zkcloud.git'
genesis: https://snapshots.polkachu.com/testnet-genesis/zkcloud/genesis.json
minimum_gas_price: '0.001uproof'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:31256'
upgrade_folder: v0.2.0
custom_port_prefix: 312
update_website_immediately: true
# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
