---
config_port_changes:
  'laddr = "tcp://0.0.0.0:26656"': 'laddr = "tcp://0.0.0.0:{{ custom_port_prefix }}656"'
  'laddr = "tcp://127.0.0.1:26657"': 'laddr = "tcp://127.0.0.1:{{ custom_port_prefix }}657"'
  'proxy_app = "tcp://127.0.0.1:26658"': 'proxy_app = "tcp://127.0.0.1:{{ custom_port_prefix }}658"'
  'prometheus_listen_addr = ":26660"': 'prometheus_listen_addr = ":{{ custom_port_prefix }}660"'
  'pprof_laddr = "localhost:6060"': 'pprof_laddr = "localhost:{{ custom_port_prefix }}060"'
app_port_changes:
  'address = "tcp://0.0.0.0:1317"': 'address = "tcp://0.0.0.0:{{ custom_port_prefix }}317"'
  'address = ":8080"': 'address = ":{{ custom_port_prefix }}080"'
  'address = "0.0.0.0:9090"': 'address = "0.0.0.0:{{ custom_port_prefix }}090"'
  'address = "0.0.0.0:9091"': 'address = "0.0.0.0:{{ custom_port_prefix }}091"'
pruning_main_backup:
  'pruning = "': 'pruning = "custom"'
  'pruning-keep-recent = "': 'pruning-keep-recent = "100"'
  'pruning-interval = "': 'pruning-interval = "19"'
  'snapshot-interval = ': 'snapshot-interval = 0'
pruning_relayer:
  'pruning = "': 'pruning = "custom"'
  'pruning-keep-recent = "': 'pruning-keep-recent = "40000"'
  'pruning-keep-every = "': 'pruning-keep-every = "2000"'
  'pruning-interval = "': 'pruning-interval = "17"'
  'snapshot-interval = ': 'snapshot-interval = 2000'
  'snapshot-keep-recent = ': 'snapshot-keep-recent= 5'
pruning_test:
  'pruning = "': 'pruning = "custom"'
  'pruning-keep-recent = "': 'pruning-keep-recent = "8000"'
  'pruning-keep-every = "': 'pruning-keep-every = "2000"'
  'pruning-interval = "': 'pruning-interval = "17"'
  'snapshot-interval = ': 'snapshot-interval = 2000'
  'snapshot-keep-recent = ': 'snapshot-keep-recent= 2'
