---
- name: Update apt repo and cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages on servers
  apt:
    upgrade: dist

- name: Check if a reboot is needed on all servers
  stat:
    path: '/var/run/reboot-required'
    get_md5: no
  register: reboot_required_file

- name: Reboot the box if kernel updated
  reboot:
    msg: 'Reboot initiated by Ansible for kernel updates'
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
