network: quicksilver
folder: '.quicksilverd'
daemon: quicksilverd
chain_id: killerqueen-1
node_version: v0.4.0
repo: https://github.com/ingenuity-build/quicksilver.git
genesis: 'https://raw.githubusercontent.com/ingenuity-build/testnets/main/killerqueen/genesis.json'
peers: '95f3d663ac795966b6bcc2fa99e74568d434c957@165.227.147.158:36366,07bb0fd7af9dc819bb5bb850ea5d870281c3adfa@167.235.74.230:26656,e7a9a639af5f23b9f766ad240f8619881b4918fe@147.182.144.160:11656,fcfcf2402f106b300ada70fce2ff52603290c43a@104.248.112.44:11656,0d4204f3c0aa0897f30cc76a604da2dfced12d8c@167.235.229.110:11656,dd6a22d3abbf5a0b41caab7f8f07dfe5450dac22@161.97.136.141:26651,4f35ab6008fc46cc50b103a337ec2266400eca2e@148.251.50.79:26656,93636cb24b9710413d581043edfbf957eebb7f09@178.128.116.150:11656,4b994f21ada989568ff61167b9fa803028d8a87c@212.71.251.165:26656,df4ac5dab326503be2c9d26abf1109eb2338088e@65.21.4.129:11656,c2baebdc5468ef0e86f7850bdd8cd91e20fa53b2@65.108.71.92:48656'
custom_port_prefix: 11
